// tag::main[]

=== Undertow 시작하기

Undertow를 시작할 수 있는 방법이 몇 가지 있습니다.

==== Wildfly

link:http://wildfly.org[Wildfly] 버전 8.0부터 Undertow는 Wildfly의 웹 서버 컴포넌트였습니다. 만약 당신이 Wildfly를 사용하고 있다면, 이미 Undertow를 사용하고 있는 것입니다.

==== 메이븐

Undertow는 maven을 이용해서 사용할 수 있으며, maven central에 최신 버전이 동기화됩니다. Undertow는 세가지로 나뉘어진 컴포넌트가 제공됩니다.

Core:: 넌블로킹 핸들러와 웹소켓이 지원되는 Undertow 코어
Servlet:: 서블릿 4.0 지원
Websockets JSR: 'Java API for Websockets (JSR-356)' 표준을 지원

Maven 프로젝트에서 Undertow를 사용하기 위해서는 pom.xml 파일에 다음 항목을 포함시키고, `undertow.version` 속성에 사용하고자 하는 Undertow의 버전을 지정하십시오.

[source,xml]
----
<dependency>
	<groupId>io.undertow</groupId>
	<artifactId>undertow-core</artifactId>
	<version>${undertow.version}</version>
</dependency>
<dependency>
	<groupId>io.undertow</groupId>
	<artifactId>undertow-servlet</artifactId>
	<version>${undertow.version}</version>
</dependency>
<dependency>
	<groupId>io.undertow</groupId>
	<artifactId>undertow-websockets-jsr</artifactId>
	<version>${undertow.version}</version>
</dependency>
----


==== 직접 다운로드

Undertow는 link:http://mvnrepository.com/search?q=io.undertow[maven 저장소]에서 직접 다운로드 받는 것도 가능합니다.

Undertow는 link:http://xnio.jboss.org[XNIO]와 link:https://github.com/jboss-logging/jboss-logging[JBoss Logging]에 의존하므로, 이 둘의 다운로드도 필요할 것입니다.

==== 직접 빌드하기

가장 최신 코드를 얻기 위해, Undertow를 직접 빌드할 수도 있습니다.

*준비사항*

- JDK8이나 그 이상 버전
- Maven 3.1
- git

Undertow의 빌드는 쉽습니다. 그냥 아래 단계를 따라가면 됩니다.

Maven 설정하기::
link:https://developer.jboss.org/wiki/MavenGettingStarted-Users[이 문서]를 따라서, Maven이 JBoss Maven 저장소를 사용하도록 설정하세요.

git 저장소 clone::
`git clone https://github.com/undertow-io/undertow.git`

Undertow 빌드::
`cd undertow && mvn install`

빌드에는 모든 테스트를 수행하고 에러가 없어야 합니다.

[WARNING]
If you attempt to build with `-Dmaven.test.skip=true` for your initial build the build will fail, as the core test
jar will not be built and the Servlet module has a test scoped dependency on this jar. Either use `-DskipTests`, or
just let the tests run the first time.

// end::main[]
