// tag::main[]

=== Undertow 시작하기

Undertow를 시작할 수 있는 방법이 몇 가지 있습니다.

==== Wildfly

link:http://wildfly.org[Wildfly] 버전 8.0부터 Undertow는 Wildfly의 웹 서버 컴포넌트였습니다. 만약 당신이 Wildfly를 사용하고 있다면, 이미 Undertow를 사용하고 있는 것입니다.

==== Maven

Undertow는 maven을 이용해서 사용할 수 있으며, maven central에 최신 버전이 동기화됩니다. Undertow는 세가지로 나뉘어진 컴포넌트가 제공됩니다.

Core:: 넌블로킹 핸들러와 웹소켓이 지원되는 Undertow 코어
Servlet:: 서블릿 4.0 지원
Websockets JSR: 'Java API for Websockets (JSR-356)' 표준을 지원

In order to use Undertow in your maven projects just include the following section in your pom.xml, and set the `undertow.version`
property to whatever version of Undertow you wish to use. Only the core artifact is required, if you are not using
Servlet or JSR-356 then those artifacts are not required.

[source,xml]
----
<dependency>
	<groupId>io.undertow</groupId>
	<artifactId>undertow-core</artifactId>
	<version>${undertow.version}</version>
</dependency>
<dependency>
	<groupId>io.undertow</groupId>
	<artifactId>undertow-servlet</artifactId>
	<version>${undertow.version}</version>
</dependency>
<dependency>
	<groupId>io.undertow</groupId>
	<artifactId>undertow-websockets-jsr</artifactId>
	<version>${undertow.version}</version>
</dependency>
----


==== Direct Download

Undertow can also be directly downloaded from the link:http://mvnrepository.com/search?q=io.undertow[maven repository].

Undertow depends on link:http://xnio.jboss.org[XNIO] and link:https://github.com/jboss-logging/jboss-logging[JBoss Logging],
which will need to be downloaded as well.

==== Build it yourself

In order to get the most up to date code you can build Undertow yourself.

*Prerequisites*

- JDK8 or higher
- Maven 3.1
- git

Building Undertow is easy, just follow these steps:

Configure Maven::
Follow the instructions link:https://developer.jboss.org/wiki/MavenGettingStarted-Users[here] to configure Maven to use
the JBoss Maven repository.

Clone the git repo::
`git clone https://github.com/undertow-io/undertow.git`

Build Undertow::
`cd undertow && mvn install`

The build should run all tests and complete without errors.

[WARNING]
If you attempt to build with `-Dmaven.test.skip=true` for your initial build the build will fail, as the core test
jar will not be built and the Servlet module has a test scoped dependency on this jar. Either use `-DskipTests`, or
just let the tests run the first time.

// end::main[]
